---
- name: Converge
  hosts: all
  become: true

  vars:
    postgresql_use_pgdg_repo: true

    postgresql_extensions_packages:
      - postgresql-17-postgis-3

    postgresql_databases:
      - name: example
        extensions:
          - postgis

    postgresql_extensions:
      - name: pg_trgm
        db: example

    postgresql_users:
      - name: jdoe
        password: "testpassword123"
      - name: longjohnsilver
        password: "testpassword456"
    postgresql_privs:
      - db: example
        roles: jdoe
        type: database
        privs: ALL
      - db: example
        roles: longjohnsilver
        objs: ALL_IN_SCHEMA
        privs: ALL

  roles:
    - role: okassov.postgresql
